# Generated by Django 5.0.2 on 2024-03-10 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 10, 10, 45, 2, 894715, tzinfo=datetime.timezone.utc)),
        ),
    ]
